### PR TITLE
Grad optimization

### PR DESCRIPTION
**Pull request by lynnmunday**
This adds in an adjoint solve to compute the gradient for force inversion to use taocg.

### CODE REVIEW

**Comment by lynnmunday** [comment]
@dewenyushu only the top commit is for this, the rest are from the gradient free pr

**Comment by dewenyushu** [comment]
There are only 2 new commits different #4. It is easier if we merge #4, rebase, and work on this one. Otherwise there are so many changes in this PR that overlaps #4

**Comment by lynnmunday** [comment]
> There are only 2 new commits different #4. It is easier if we merge #4, rebase, and work on this one. Otherwise there are so many changes in this PR that overlaps #4

@dewenyushu I don't know how to do this.  I think I can only get rid of the extra commits if I get the other pr merged.

**Comment by dewenyushu** [comment]
> > There are only 2 new commits different #4. It is easier if we merge #4, rebase, and work on this one. Otherwise there are so many changes in this PR that overlaps #4
> 
> @dewenyushu I don't know how to do this. I think I can only get rid of the extra commits if I get the other pr merged.

let's get #4 merged first

**Comment by lynnmunday** [comment]
I think #4 is ready to merge

**Comment by lynnmunday** [comment]
@dewenyushu Everything should be cleaned up now between the two prs.  Thanks for merging the other one.  I won't add anything else to this pr unless it is a fix.  I'm trying to make a bigger example than the one I've been using.

**Comment by lynnmunday** [comment]
@dewenyushu we can talk on Monday but if you look at the gradient optimization problem in multiapp and set the diracKernel values to zero in forward.i, you will see that it takes a lot of iterations to solve with taonm and that the gradient doesn't really help and that it still takes lots of iterations with taocg.  I thought the gradient was wrong so @zachmprince  helped me put in some tao finite difference checks and the gradient is correct.  So then I solved it with the tao finite difference hessian and it converges in only a few iterations.  So I think we need to implement the Hessian method for this to be useful.  These examples are in multiapp/.  The grad_free_opt/pp_transfers uses taonm, taocg and taontr with finite difference hessian and gradient.  The grad_opt directory uses the adjoint for taocg and then also runs a check that the adjoint gradient is the same as the finite difference gradient

**Comment by dewenyushu** [comment]
> @dewenyushu we can talk on Monday but if you look at the gradient optimization problem in multiapp and set the diracKernel values to zero in forward.i, you will see that it takes a lot of iterations to solve with taonm and that the gradient doesn't really help and that it still takes lots of iterations with taocg. I thought the gradient was wrong so @zachmprince helped me put in some tao finite difference checks and the gradient is correct. So then I solved it with the tao finite difference hessian and it converges in only a few iterations. So I think we need to implement the Hessian method for this to be useful. These examples are in multiapp/. The grad_free_opt/pp_transfers uses taonm, taocg and taontr with finite difference hessian and gradient. The grad_opt directory uses the adjoint for taocg and then also runs a check that the adjoint gradient is the same as the finite difference gradient

Thanks @lynnmunday , I will take a look by changing the tao options as you indicated. 

Murthy's code converges the best with both Gradient and Hessian, just as what you see here. With no Hessian, it converges much slower. But I have not checked how it would perform with neither Hessian nor Gradient. I would assume using Gradient is still outperforming the case without Gradient. But maybe Gradient is not helping much, and what you see is correct. I am not sure.

**Review by dewenyushu — APPROVED** [review]
Thanks for making the change! Looks good to me.

**Pull request merged**
